from typing import Literal, Optional

from pydantic import BaseModel, Field


class FanInteraction(BaseModel):
    """
    Operational data model representing an inbound request or inquiry from a fan.
    
    This captures raw audio transcriptions from mobile devices, physical help kiosks, 
    or volunteer radios, allowing the AI triage system to process it regardless of 
    the fan's native language.
    """
    raw_audio_transcript: str = Field(
        ...,
        description="The literal transcribed text of the fan's spoken request."
    )
    detected_language: Optional[str] = Field(
        default=None,
        description="The detected source language, if known by the edge device (e.g., 'es', 'fr')."
    )
    location_zone: str = Field(
        ...,
        description="The physical location or coordinate zone where the interaction occurred (e.g., 'CONCOURSE_C')."
    )


class ActionableTask(BaseModel):
    """
    Structured operational directive generated by the AI triage system.
    
    This payload normalizes chaotic, multilingual crowd requests into standardized, 
    English-language tasks that can be deterministically routed to the appropriate 
    stadium staff units.
    """
    translated_english_summary: str = Field(
        ...,
        description="A concise, actionable English translation and summary of the fan's need."
    )
    priority_level: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"] = Field(
        ...,
        description="Calculated severity of the interaction to drive SLA and dispatch routing."
    )
    required_staff_role: str = Field(
        ...,
        description="The specific operational unit required to handle this task (e.g., 'MEDICAL', 'SECURITY', 'USHER', 'CLEANING')."
    )
